/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHederaTokenService,
  IHederaTokenServiceInterface,
} from "../../../contracts/AgriYield.sol/IHederaTokenService";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "associateToken",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "accountID",
                type: "address",
              },
              {
                internalType: "int64",
                name: "amount",
                type: "int64",
              },
            ],
            internalType: "struct IHederaTokenService.AccountAmount[]",
            name: "transfers",
            type: "tuple[]",
          },
        ],
        internalType: "struct IHederaTokenService.TransferList",
        name: "transferList",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            components: [
              {
                internalType: "address",
                name: "accountID",
                type: "address",
              },
              {
                internalType: "int64",
                name: "amount",
                type: "int64",
              },
            ],
            internalType: "struct IHederaTokenService.AccountAmount[]",
            name: "transfers",
            type: "tuple[]",
          },
          {
            internalType: "int64[]",
            name: "nftTransfers",
            type: "int64[]",
          },
        ],
        internalType: "struct IHederaTokenService.TokenTransferList[]",
        name: "tokenTransfers",
        type: "tuple[]",
      },
    ],
    name: "cryptoTransfer",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isKyc",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "int64",
        name: "amount",
        type: "int64",
      },
      {
        internalType: "bytes[]",
        name: "metadata",
        type: "bytes[]",
      },
    ],
    name: "mintToken",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "int64",
        name: "amount",
        type: "int64",
      },
    ],
    name: "transferToken",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHederaTokenService__factory {
  static readonly abi = _abi;
  static createInterface(): IHederaTokenServiceInterface {
    return new Interface(_abi) as IHederaTokenServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHederaTokenService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHederaTokenService;
  }
}
